---
deployment:
  tasks:
    - export DEPLOYPATH=/home/theamazinraven/docusaurus.raedickerson.dev/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - bin/cp/docusaurus.raedickerson.dev/ -R img $DEPLOYPATH
