---
deployment:
  tasks:
    - export DEPLOYPATH=/home/theamazinraven/docusaurus.raedickerson.dev/
    - /bin/cp/pages index.js $DEPLOYPATH
    - /bin/cp/css custom.css $DEPLOYPATH
    - bin/cp/docusaurus.raedickerson.dev/ -R img $DEPLOYPATH
